#!/usr/bin/env node
// Single-source-of-truth wire codegen.
//
// Reads schema.json + VERSION and emits BOTH the C++ header and the TypeScript
// decoder so the binary contract cannot drift between the engine and the
// browser. CI regenerates and `git diff --exit-code`s the outputs, which is what
// makes the "single source of truth" claim enforceable rather than aspirational.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const schema = JSON.parse(readFileSync(join(here, 'schema.json'), 'utf8'));
const version = readFileSync(join(here, 'VERSION'), 'utf8').trim();
const [major] = version.split('.');

// magic string as a little-endian uint32.
const magic = [...schema.magic].reduce((acc, ch, i) => acc | (ch.charCodeAt(0) << (8 * i)), 0) >>> 0;

const SIZE = { u16: 2, u32: 4, u64: 8, f32: 4, f64: 8 };
const CPP = { u16: 'std::uint16_t', u32: 'std::uint32_t', u64: 'std::uint64_t', f32: 'float', f64: 'double' };
const TS_VIEW = { u32: 'Uint32Array', f32: 'Float32Array', f64: 'Float64Array' };
const DV_GET = { u16: 'getUint16', u32: 'getUint32', u64: 'getBigUint64', f32: 'getFloat32', f64: 'getFloat64' };
const DV_SET = { u16: 'setUint16', u32: 'setUint32', u64: 'setBigUint64', f32: 'setFloat32', f64: 'setFloat64' };

const headerSize = schema.header.reduce((s, f) => s + SIZE[f.type], 0);

// ---------------------------------------------------------------- C++ header
function genCpp() {
  const L = [];
  L.push('// GENERATED by proto/codegen.mjs from proto/schema.json + proto/VERSION.');
  L.push('// DO NOT EDIT. Run `node proto/codegen.mjs` to regenerate.');
  L.push(`// schema version ${version}`);
  L.push('#ifndef RISKSIM_RUNTIME_WIRE_GENERATED_HPP');
  L.push('#define RISKSIM_RUNTIME_WIRE_GENERATED_HPP');
  L.push('');
  L.push('#include <bit>');
  L.push('#include <cstddef>');
  L.push('#include <cstdint>');
  L.push('#include <cstring>');
  L.push('#include <optional>');
  L.push('#include <span>');
  L.push('#include <vector>');
  L.push('');
  L.push('namespace risksim::wire {');
  L.push('');
  L.push('static_assert(std::endian::native == std::endian::little,');
  L.push('              "wire protocol assumes a little-endian host");');
  L.push('');
  L.push(`inline constexpr std::uint32_t kMagic = 0x${magic.toString(16).toUpperCase()}u;`);
  L.push(`inline constexpr std::uint16_t kSchemaVersionMajor = ${major};`);
  L.push(`inline constexpr std::size_t kHeaderSize = ${headerSize};`);
  L.push('');
  L.push('enum class MsgType : std::uint16_t {');
  for (const m of schema.messages) L.push(`    k${m.name} = ${m.type_id},`);
  L.push('};');
  L.push('');
  // Header struct.
  L.push('struct Header {');
  for (const f of schema.header) L.push(`    ${CPP[f.type]} ${f.name} = 0;`);
  L.push('};');
  L.push('');
  L.push('namespace detail {');
  L.push('template <class T>');
  L.push('inline void put(std::byte*& p, T v) noexcept { std::memcpy(p, &v, sizeof(T)); p += sizeof(T); }');
  L.push('template <class T>');
  L.push('inline T get(const std::byte*& p) noexcept { T v; std::memcpy(&v, p, sizeof(T)); p += sizeof(T); return v; }');
  L.push('}  // namespace detail');
  L.push('');

  for (const m of schema.messages) {
    const arraysSize = m.arrays
      .map((a) => `${SIZE[a.type]} * fixed.${a.count}`)
      .join(' + ');
    const fixedSize = m.fixed.reduce((s, f) => s + SIZE[f.type], 0);

    // Fixed-field struct.
    L.push(`struct ${m.name}Fixed {`);
    for (const f of m.fixed) L.push(`    ${CPP[f.type]} ${f.name} = 0;`);
    L.push('};');
    L.push('');

    // Builder.
    const spanParams = m.arrays.map((a) => `std::span<const ${CPP[a.type]}> ${a.name}`).join(', ');
    L.push(`[[nodiscard]] inline std::vector<std::byte> build_${m.name.toLowerCase()}(`);
    L.push('    std::uint64_t tick_seq, std::uint64_t sim_time_ns, std::uint64_t wall_emit_ns,');
    L.push(`    const ${m.name}Fixed& fixed, ${spanParams}) {`);
    L.push(`    const std::size_t body = ${fixedSize} + (${arraysSize});`);
    L.push('    std::vector<std::byte> buf(kHeaderSize + body);');
    L.push('    std::byte* p = buf.data();');
    // header
    for (const f of schema.header) {
      if (f.name === 'magic') L.push('    detail::put(p, kMagic);');
      else if (f.name === 'version') L.push('    detail::put(p, kSchemaVersionMajor);');
      else if (f.name === 'msg_type') L.push(`    detail::put(p, static_cast<std::uint16_t>(MsgType::k${m.name}));`);
      else if (f.name === 'body_len') L.push('    detail::put(p, static_cast<std::uint32_t>(body));');
      else L.push(`    detail::put(p, ${f.name});`);
    }
    // fixed
    for (const f of m.fixed) L.push(`    detail::put(p, fixed.${f.name});`);
    // arrays
    for (const a of m.arrays) {
      L.push(`    std::memcpy(p, ${a.name}.data(), ${SIZE[a.type]} * fixed.${a.count});`);
      L.push(`    p += ${SIZE[a.type]} * fixed.${a.count};`);
    }
    L.push('    return buf;');
    L.push('}');
    L.push('');

    // View + parser.
    L.push(`struct ${m.name}View {`);
    L.push('    Header header;');
    L.push(`    ${m.name}Fixed fixed;`);
    for (const a of m.arrays) L.push(`    std::span<const ${CPP[a.type]}> ${a.name};`);
    L.push('};');
    L.push('');
    L.push(`[[nodiscard]] inline std::optional<${m.name}View> parse_${m.name.toLowerCase()}(`);
    L.push('    std::span<const std::byte> buf) {');
    L.push('    if (buf.size() < kHeaderSize) return std::nullopt;');
    L.push('    const std::byte* p = buf.data();');
    L.push('    const std::byte* end = buf.data() + buf.size();');
    L.push(`    ${m.name}View v;`);
    for (const f of schema.header) L.push(`    v.header.${f.name} = detail::get<${CPP[f.type]}>(p);`);
    L.push('    if (v.header.magic != kMagic) return std::nullopt;');
    L.push(`    if (v.header.msg_type != static_cast<std::uint16_t>(MsgType::k${m.name})) return std::nullopt;`);
    L.push(`    if (static_cast<std::size_t>(end - p) < ${fixedSize}) return std::nullopt;`);
    for (const f of m.fixed) L.push(`    v.fixed.${f.name} = detail::get<${CPP[f.type]}>(p);`);
    for (const a of m.arrays) {
      L.push(`    {`);
      L.push(`        const std::size_t n = v.fixed.${a.count};`);
      L.push(`        if (static_cast<std::size_t>(end - p) < ${SIZE[a.type]} * n) return std::nullopt;`);
      L.push(`        v.${a.name} = std::span<const ${CPP[a.type]}>(reinterpret_cast<const ${CPP[a.type]}*>(p), n);`);
      L.push(`        p += ${SIZE[a.type]} * n;`);
      L.push(`    }`);
    }
    L.push('    return v;');
    L.push('}');
    L.push('');
  }
  L.push('}  // namespace risksim::wire');
  L.push('');
  L.push('#endif  // RISKSIM_RUNTIME_WIRE_GENERATED_HPP');
  return L.join('\n') + '\n';
}

// ------------------------------------------------------------- TS decoder
function genTs() {
  const L = [];
  L.push('// GENERATED by proto/codegen.mjs from proto/schema.json + proto/VERSION.');
  L.push('// DO NOT EDIT. Run `node proto/codegen.mjs` to regenerate.');
  L.push(`// schema version ${version}`);
  L.push('/* eslint-disable */');
  L.push('');
  L.push(`export const MAGIC = 0x${magic.toString(16).toUpperCase()};`);
  L.push(`export const SCHEMA_VERSION_MAJOR = ${major};`);
  L.push(`export const HEADER_SIZE = ${headerSize};`);
  L.push('');
  L.push('export interface Header {');
  for (const f of schema.header) L.push(`  ${f.name}: ${f.type === 'u64' ? 'bigint' : 'number'};`);
  L.push('}');
  L.push('');
  for (const m of schema.messages) {
    L.push(`export const MSG_${m.name.toUpperCase()} = ${m.type_id};`);
    L.push(`export interface ${m.name} {`);
    L.push('  header: Header;');
    for (const f of m.fixed) L.push(`  ${f.name}: ${f.type === 'u64' ? 'bigint' : 'number'};`);
    for (const a of m.arrays) L.push(`  ${a.name}: ${TS_VIEW[a.type]};`);
    L.push('}');
    L.push('');
    L.push(`export function decode${m.name}(buffer: ArrayBuffer, byteOffset = 0): ${m.name} | null {`);
    L.push('  const dv = new DataView(buffer, byteOffset);');
    L.push('  if (dv.byteLength < HEADER_SIZE) return null;');
    L.push('  let o = 0;');
    L.push('  const header = {} as Header;');
    for (const f of schema.header) {
      const args = f.type === 'u16' || f.type === 'u32' || f.type === 'u64' ? 'o, true' : 'o, true';
      L.push(`  header.${f.name} = dv.${DV_GET[f.type]}(${args}); o += ${SIZE[f.type]};`);
    }
    L.push('  if (header.magic !== MAGIC) return null;');
    L.push(`  if (header.msg_type !== MSG_${m.name.toUpperCase()}) return null;`);
    L.push(`  const out = { header } as ${m.name};`);
    for (const f of m.fixed) {
      L.push(`  out.${f.name} = dv.${DV_GET[f.type]}(o, true); o += ${SIZE[f.type]};`);
    }
    L.push('  const base = byteOffset + o;');
    L.push('  let cur = base;');
    for (const a of m.arrays) {
      L.push(`  out.${a.name} = new ${TS_VIEW[a.type]}(buffer, cur, out.${a.count}); cur += ${SIZE[a.type]} * out.${a.count};`);
    }
    L.push('  return out;');
    L.push('}');
    L.push('');
  }
  return L.join('\n');
}

const cppPath = join(root, 'engine/runtime/include/risksim/runtime/wire_generated.hpp');
const tsPath = join(root, 'web/src/generated/wire.ts');
mkdirSync(dirname(cppPath), { recursive: true });
mkdirSync(dirname(tsPath), { recursive: true });
writeFileSync(cppPath, genCpp());
writeFileSync(tsPath, genTs());
console.log(`wrote ${cppPath}`);
console.log(`wrote ${tsPath}`);
