// GENERATED by proto/codegen.mjs from proto/schema.json + proto/VERSION.
// DO NOT EDIT. Run `node proto/codegen.mjs` to regenerate.
// schema version 1.0.0
#ifndef RISKSIM_RUNTIME_WIRE_GENERATED_HPP
#define RISKSIM_RUNTIME_WIRE_GENERATED_HPP

#include <bit>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <optional>
#include <span>
#include <vector>

namespace risksim::wire {

static_assert(std::endian::native == std::endian::little,
              "wire protocol assumes a little-endian host");

inline constexpr std::uint32_t kMagic = 0x4D495352u;
inline constexpr std::uint16_t kSchemaVersionMajor = 1;
inline constexpr std::size_t kHeaderSize = 36;

enum class MsgType : std::uint16_t {
    kSnapshot = 1,
};

struct Header {
    std::uint32_t magic = 0;
    std::uint16_t version = 0;
    std::uint16_t msg_type = 0;
    std::uint64_t tick_seq = 0;
    std::uint64_t sim_time_ns = 0;
    std::uint64_t wall_emit_ns = 0;
    std::uint32_t body_len = 0;
};

namespace detail {
template <class T>
inline void put(std::byte*& p, T v) noexcept { std::memcpy(p, &v, sizeof(T)); p += sizeof(T); }
template <class T>
inline T get(const std::byte*& p) noexcept { T v; std::memcpy(&v, p, sizeof(T)); p += sizeof(T); return v; }
}  // namespace detail

struct SnapshotFixed {
    std::uint32_t n_nodes = 0;
    std::uint32_t n_edges = 0;
    float var = 0;
    float es = 0;
    float total_loss = 0;
    std::uint32_t num_defaults = 0;
};

[[nodiscard]] inline std::vector<std::byte> build_snapshot(
    std::uint64_t tick_seq, std::uint64_t sim_time_ns, std::uint64_t wall_emit_ns,
    const SnapshotFixed& fixed, std::span<const float> node_health, std::span<const float> node_value, std::span<const float> node_x, std::span<const float> node_y, std::span<const std::uint32_t> edge_src, std::span<const std::uint32_t> edge_dst, std::span<const float> edge_flow) {
    const std::size_t body = 24 + (4 * fixed.n_nodes + 4 * fixed.n_nodes + 4 * fixed.n_nodes + 4 * fixed.n_nodes + 4 * fixed.n_edges + 4 * fixed.n_edges + 4 * fixed.n_edges);
    std::vector<std::byte> buf(kHeaderSize + body);
    std::byte* p = buf.data();
    detail::put(p, kMagic);
    detail::put(p, kSchemaVersionMajor);
    detail::put(p, static_cast<std::uint16_t>(MsgType::kSnapshot));
    detail::put(p, tick_seq);
    detail::put(p, sim_time_ns);
    detail::put(p, wall_emit_ns);
    detail::put(p, static_cast<std::uint32_t>(body));
    detail::put(p, fixed.n_nodes);
    detail::put(p, fixed.n_edges);
    detail::put(p, fixed.var);
    detail::put(p, fixed.es);
    detail::put(p, fixed.total_loss);
    detail::put(p, fixed.num_defaults);
    std::memcpy(p, node_health.data(), 4 * fixed.n_nodes);
    p += 4 * fixed.n_nodes;
    std::memcpy(p, node_value.data(), 4 * fixed.n_nodes);
    p += 4 * fixed.n_nodes;
    std::memcpy(p, node_x.data(), 4 * fixed.n_nodes);
    p += 4 * fixed.n_nodes;
    std::memcpy(p, node_y.data(), 4 * fixed.n_nodes);
    p += 4 * fixed.n_nodes;
    std::memcpy(p, edge_src.data(), 4 * fixed.n_edges);
    p += 4 * fixed.n_edges;
    std::memcpy(p, edge_dst.data(), 4 * fixed.n_edges);
    p += 4 * fixed.n_edges;
    std::memcpy(p, edge_flow.data(), 4 * fixed.n_edges);
    p += 4 * fixed.n_edges;
    return buf;
}

struct SnapshotView {
    Header header;
    SnapshotFixed fixed;
    std::span<const float> node_health;
    std::span<const float> node_value;
    std::span<const float> node_x;
    std::span<const float> node_y;
    std::span<const std::uint32_t> edge_src;
    std::span<const std::uint32_t> edge_dst;
    std::span<const float> edge_flow;
};

[[nodiscard]] inline std::optional<SnapshotView> parse_snapshot(
    std::span<const std::byte> buf) {
    if (buf.size() < kHeaderSize) return std::nullopt;
    const std::byte* p = buf.data();
    const std::byte* end = buf.data() + buf.size();
    SnapshotView v;
    v.header.magic = detail::get<std::uint32_t>(p);
    v.header.version = detail::get<std::uint16_t>(p);
    v.header.msg_type = detail::get<std::uint16_t>(p);
    v.header.tick_seq = detail::get<std::uint64_t>(p);
    v.header.sim_time_ns = detail::get<std::uint64_t>(p);
    v.header.wall_emit_ns = detail::get<std::uint64_t>(p);
    v.header.body_len = detail::get<std::uint32_t>(p);
    if (v.header.magic != kMagic) return std::nullopt;
    if (v.header.msg_type != static_cast<std::uint16_t>(MsgType::kSnapshot)) return std::nullopt;
    if (static_cast<std::size_t>(end - p) < 24) return std::nullopt;
    v.fixed.n_nodes = detail::get<std::uint32_t>(p);
    v.fixed.n_edges = detail::get<std::uint32_t>(p);
    v.fixed.var = detail::get<float>(p);
    v.fixed.es = detail::get<float>(p);
    v.fixed.total_loss = detail::get<float>(p);
    v.fixed.num_defaults = detail::get<std::uint32_t>(p);
    {
        const std::size_t n = v.fixed.n_nodes;
        if (static_cast<std::size_t>(end - p) < 4 * n) return std::nullopt;
        v.node_health = std::span<const float>(reinterpret_cast<const float*>(p), n);
        p += 4 * n;
    }
    {
        const std::size_t n = v.fixed.n_nodes;
        if (static_cast<std::size_t>(end - p) < 4 * n) return std::nullopt;
        v.node_value = std::span<const float>(reinterpret_cast<const float*>(p), n);
        p += 4 * n;
    }
    {
        const std::size_t n = v.fixed.n_nodes;
        if (static_cast<std::size_t>(end - p) < 4 * n) return std::nullopt;
        v.node_x = std::span<const float>(reinterpret_cast<const float*>(p), n);
        p += 4 * n;
    }
    {
        const std::size_t n = v.fixed.n_nodes;
        if (static_cast<std::size_t>(end - p) < 4 * n) return std::nullopt;
        v.node_y = std::span<const float>(reinterpret_cast<const float*>(p), n);
        p += 4 * n;
    }
    {
        const std::size_t n = v.fixed.n_edges;
        if (static_cast<std::size_t>(end - p) < 4 * n) return std::nullopt;
        v.edge_src = std::span<const std::uint32_t>(reinterpret_cast<const std::uint32_t*>(p), n);
        p += 4 * n;
    }
    {
        const std::size_t n = v.fixed.n_edges;
        if (static_cast<std::size_t>(end - p) < 4 * n) return std::nullopt;
        v.edge_dst = std::span<const std::uint32_t>(reinterpret_cast<const std::uint32_t*>(p), n);
        p += 4 * n;
    }
    {
        const std::size_t n = v.fixed.n_edges;
        if (static_cast<std::size_t>(end - p) < 4 * n) return std::nullopt;
        v.edge_flow = std::span<const float>(reinterpret_cast<const float*>(p), n);
        p += 4 * n;
    }
    return v;
}

}  // namespace risksim::wire

#endif  // RISKSIM_RUNTIME_WIRE_GENERATED_HPP
